### ISSUE TITLE
Html report does not show Old and New versions as well as Semantic Versioning field

### ISSUE THREAD

**Issue by brestler** [melix/japicmp-gradle-plugin#31]
Screen shot attached below. For now, I'm forced to upgrade html directly to set versions. As for semantic versioning I'll have to parse html in order to find some (*) or (!) changes and understand  which version should I increment. This functionality was present in Maven plugin.
Am I missing something or it's not implemented yet? And if so, are there any plans to implement it?

![na_problem](https://user-images.githubusercontent.com/27245619/56900978-c04b1080-6a9f-11e9-971a-2ce68e41ef5a.jpg)

**Comment by jkwatson** [comment]
This is also true of the text report. It looks like this at the top of the output (for example):

```
Comparing source compatibility of  against 
No changes.
```
