### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by centic9** [melix/japicmp-gradle-plugin#6]
The current release 0.1.1 does not contain a few of the things that are described in the README, e.g. htmlOutputFile and onlyBinaryIncompatibleModified are missing and there is a newer JApicmp 0.9.1 available as well.

Anything that I can help with to get an updated release?

**Comment by melix** [comment]
Let me see if I can get it out quickly.

**Comment by melix** [comment]
I have just released 0.1.2: https://plugins.gradle.org/plugin/me.champeau.gradle.japicmp

Best regards,

**Comment by centic9** [comment]
Wow, that was fast, thanks a lot!
