### ISSUE TITLE
>0.16.0: Cannot compare versions because the number of old versions is different than the number of new versions

### ISSUE THREAD

**Issue by lalithaawgu** [melix/japicmp-gradle-plugin#60]
I am configuring a multimodule maven project to use the maven plugin.
But I see this error when i specify 4 jars in <newVersions/> to compare against 4 jars in <oldVersions/>
If i skip <newVersions> entirely build succeeds but doesnt report missing classes.
This seems to be an issue only with v0.16.0 onwards, doesnt happen in v0.15.7.

Is it possible to compare oldVersion artifact(does NOT pull the classpath dependencies ) against the newVersion classpath dependencies(is pulled in automatically which is good) 

Caused by: japicmp.exception.JApiCmpException: Cannot compare versions because the number of old versions is different than the number of new versions.

<dependency>
    <groupId>com.github.siom79.japicmp</groupId>
    <artifactId>japicmp-maven-plugin</artifactId>
    <version>0.16.0</version>
</dependency>

**Comment by melix** [comment]
You are referring to the Maven plugin. This is the Gradle plugin.

**Comment by lalithaawgu** [comment]
Sorry about that. Thanks for your response.
