### ISSUE TITLE
HTML reporting fails with JDK17 and recent gradle versions

### ISSUE THREAD

**Issue by paulk-asert** [melix/japicmp-gradle-plugin#62]
See:
https://ci.groovy-lang.org/buildConfiguration/Groovy_CheckMasterWithCoverageJdk17/15620?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true

Stacktrace summary:
```
java.security.PrivilegedActionException: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
03:45:35     at java.base/java.security.AccessController.doPrivileged(AccessController.java:573)
03:45:35     at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.<clinit>(Injector.java:197)
03:45:35     at com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:81)
03:45:35     at com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:125)
...
03:45:35     at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:514)
...
03:45:35     at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:165)
...
03:45:35     at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:662)
03:45:35     at japicmp.output.xml.XmlOutputGenerator.createXmlDocumentAndSchema(XmlOutputGenerator.java:119)
```

It appears that the current `resolveJaxb` processing isn't sufficient for all Java versions.

Potential fix (moves to a later JAXB implementation):
https://github.com/Goooler/japicmp-gradle-plugin/pull/13/

**Comment by thc202** [comment]
That only happens when not using the rich report.

**Comment by paulk-asert** [comment]
That is also where I went to look when it wasn't working and indeed that seemed to be the case. I couldn't see any attempt to customise the classpath with a newer JAXB implementation either. But I didn't try to debug both in parallel and work out why - this was just to fix things. We are using the XML reporting.

**Comment by paulk-asert** [comment]
Yes, the rich reporting also seems to work.

**Comment by Goooler** [comment]
> That is curious, we're using this plugin with JDK 17 and Gradle 8.2 in Micronaut without any problem 🤔

Cause the tests was pinned on Java 8 by toolchain using.

**Comment by Goooler** [comment]
@melix I believe this issue had been fixed in #63, can we release a new version?

**Comment by Goooler** [comment]
Verified 0.4.2 in https://github.com/apache/groovy/pull/1925, it works well!

**Comment by paulk-asert** [comment]
New version works, thanks!

**Comment by melix** [comment]
Thanks for the contributions folks!
