### ISSUE TITLE
Release version 0.4.3 from master

### ISSUE THREAD

**Issue by peternied** [melix/japicmp-gradle-plugin#72]
The latest release tag is 10 months old and there have been ~36 commits [1] since it was published.  Consumers such as OpenSearch [2] would love to get the latest version.

- [1] https://github.com/melix/japicmp-gradle-plugin/compare/RELEASE_0_4_2...master
- [2] https://github.com/opensearch-project/OpenSearch/pull/13703#discussion_r1621347366

**Comment by melix** [comment]
0.4.3 is out, thanks for your patience!
